version: "3.7"

services:
  elasticsearch:
    image: elasticsearch:7.6.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      xpack.license.self_generated.type: trial
    networks:
      - elk

  kibana:
    image: kibana:7.6.0
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: 'http://elasticsearch:9200'
    networks:
      - elk

  web:
    build: .
    ports:
      - 80:80
    volumes:
      - "./public:/var/www/html"
      - "./src:/usr/local/lib/php/src"
    networks:
      - elk

networks:
  elk:
    driver: bridge
